language: ruby
dist: trusty
group: beta
cache: bundler

services:
  - redis-server

branches:
  only: [master]

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7

env:
  - RAILS_VERSION=4
  - RAILS_VERSION=5
  - RAILS_VERSION=0

addons:
  apt:
    packages:
      - haveged

before_install:
  - service haveged start
  - ruby -e 'gempaths = `gem env gempath`.split(":"); gempaths.each { |gempath| Dir.glob(gempath.strip + "/specifications/**/bundler-*.gemspec").each { |p| File.delete(p) } }' 
  - gem install bundler -v '1.17'

matrix:
  include:
    - rvm: jruby-9.2.11.1
      env: JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M" RAILS_VERSION=4
    - rvm: jruby-9.2.11.1
      env: JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M" RAILS_VERSION=5
    - rvm: 2.7
      env: RUBYOPT="--enable-frozen-string-literal --debug=frozen-string-literal"
    - rvm: ruby-head
      env: RAILS_VERSION=0
  exclude:
    - rvm: 2.7
      env: RAILS_VERSION=4

  allow_failures:
    - rvm: ruby-head
